### ISSUE TITLE
This is a test from Cliff Kwok on how to use the template

### ISSUE THREAD

**Issue by cliffkwok** [khuyentran1401/machine-learning-articles#83]
## TL;DR
this is a new summary 
## Key Takeaways
* 
* 

## Useful Code Snippets
```
import pandas as pd
df = pd.read_csv('')
```

## Useful Tools
* 
*

**Comment by khuyentran1401** [comment]
Hope this test is useful for you to know how to use a template. Would be great to see a particular article on this issue. You don't need to fill in every section, of course. Sometimes I just write a one-sentence summary
